class SawAgent < Formula
  desc "SAW remote agent - pairs a machine with a SAW cloud workspace"
  homepage "https://github.com/LenderCom/saw-agent"
  version "0.1.2"

  # Source moved off this tap's own releases to LenderCom/saw-agent-releases as of 0.1.2 — these
  # four url/sha256 pairs are generated by script/bump-formula.rb from that release's minisign-signed
  # manifest.json. saw-agent's stable release workflow still does NOT dispatch the receiving
  # .github/workflows/bump-formula.yml here (plan §2.7/§2.11 ticket C8 is unwired), so each stable cut
  # is bumped by running that script by hand until it does.
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/v0.1.2/saw-agent_v0.1.2_darwin_arm64.tar.gz"
      sha256 "29b359284d356c51a8bea04f4970515f2cbdfe60df3fde3f942a89594bfb0824"
    else
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/v0.1.2/saw-agent_v0.1.2_darwin_amd64.tar.gz"
      sha256 "89f0fc41766ad633291da2d61c486978716ce42110ff2b73f39976763cecf593"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/v0.1.2/saw-agent_v0.1.2_linux_arm64.tar.gz"
      sha256 "123015c08b6fc7136ecf3e5ac20a48fada16ac13ba2078cf80ef88407292689b"
    else
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/v0.1.2/saw-agent_v0.1.2_linux_amd64.tar.gz"
      sha256 "8c6208a90548bd233518032e2418659448a37b1b415f73fef0781d9de3e0e525"
    end
  end

  def install
    # The keg carries the real, versioned binary; it is never the thing on PATH. `bin/saw-agent`
    # is a small dispatch shim (see #shim_script) that prefers a self-updated
    # ~/.saw/bin/saw-agent when present, so `brew upgrade` always refreshes a trusted fallback
    # without fighting an agent that has since taken over its own updates (plan §2.6).
    libexec.install "saw-agent"
    (bin/"saw-agent").write shim_script
    chmod 0755, bin/"saw-agent"
  end

  def shim_script
    <<~SH
      #!/bin/bash
      # Generated by Formula/saw-agent.rb — do not edit directly.
      managed="$HOME/.saw/bin/saw-agent"
      keg="#{opt_libexec}/saw-agent"

      # An executable managed-path file is not proof it RUNS: a truncated, wrong-arch, or
      # otherwise corrupt binary is still `-x` but ENOEXEC on exec, and bash's `exec` on an
      # ENOEXEC file falls back to reinterpreting it as a shell script (or kills the shell) —
      # it does NOT fall through to the next line. So probe it first with a fast, side-effect-free
      # flag: `-version` prints and exits immediately, unlike a bare invocation which would boot
      # the daemon. Only exec the managed copy once the probe proves it actually runs.
      if [ -x "$managed" ] && "$managed" -version >/dev/null 2>&1; then
        exec "$managed" "$@"
      fi

      exec "$keg" "$@"
    SH
  end

  def caveats
    <<~EOS
      Next: pair this machine with a SAW cloud workspace
      ===================================================

      1. Easiest — in the browser, open your SAW workspace, go to Agents, and click
         "Add remote agent". The wizard mints a one-time pair code and hands you the
         exact command below, already filled in — copy, paste, done.

      2. Direct — a workspace operator mints a code (`saw machines pair-code`, or the
         same wizard) and gives it to you:

           SAW_CLOUD_ORG=<org-id> \\
             SAW_CLOUD_PAIR_CODE=<code> \\
             saw-agent --cloud

      3. Self-pair your OWN signed-in machine — no code needed:

           SAW_CLOUD_SELF_PAIR=1 SAW_CLOUD_ORG=<org-id> saw-agent --cloud

         (needs SAW_CLOUD_USER_TOKEN — a signed-in user session bearer)

      Every cloud attach also needs your workspace's cloud origins — the compiled agent
      has no built-in default, so set these once (the in-app wizard's command already
      includes them for you):

        SAW_CLOUD_AGENTS_URL=https://agents.sawrun.com
        SAW_CLOUD_ACCOUNTS_URL=https://accounts.sawrun.com
        SAW_CLOUD_REALTIME_URL=https://realtime.sawrun.com
        SAW_CLOUD_WORKSPACE_URL=https://workspace.sawrun.com

      Chasing the dev/internal cloud instead of production? Install `saw-agent-dev`
      (`brew install lendercom/tap/saw-agent-dev`) — it tracks the latest dev-channel
      build and its caveats print the matching *.dev.sawrun.com origins.

      Once paired, `saw-agent --cloud` IS the long-lived agent process — it stays in the
      foreground; Ctrl-C (or closing the terminal) stops it, and re-running the same
      command brings it back. This formula does not install a launchd/systemd unit — the
      `curl -fsSL https://get.sawrun.com/agent | sh` installer does, if you want the agent
      to survive reboots without a formula-managed service.


      How this installs
      ==================

      saw-agent installs as a keg-fallback + shim pair, not a single binary:
        - #{opt_bin}/saw-agent is a dispatch shim.
        - #{opt_libexec}/saw-agent is this keg's pinned, versioned binary.

      The shim always prefers a healthy ~/.saw/bin/saw-agent (verified with a fast `-version`
      probe, not just executable-bit) over the keg fallback. Nothing here bootstraps that
      managed copy automatically — once the daemon service is running, tell it to adopt
      self-updates itself:

        saw-agent self-update

      The RUNNING service binary is what installs itself into ~/.saw/bin/saw-agent; the shim
      then picks up that self-updating copy on its next start. `brew upgrade` never touches
      ~/.saw/bin — it only refreshes the keg fallback, so a broken self-update still has a
      working, signed binary underneath it.
    EOS
  end

  test do
    assert_match "saw-agent v0.1.0", shell_output("#{bin}/saw-agent --version")
  end
end
