class SawAgentDev < Formula
  desc "SAW remote agent - dev channel, tracks latest saw-agent-releases pre-release"
  homepage "https://github.com/LenderCom/saw-agent"
  version "0.1.3-dev.1567+g639c3f3d"

  # Dev-channel builds cut several times a day from LenderCom/saw-agent-releases
  # (tags dev-vX.Y.Z-dev.N). .github/workflows/bump-formula-dev.yml keeps this pinned to
  # the latest one automatically — see that workflow + script/bump-formula.rb (shared with
  # the stable saw-agent formula; it takes the formula path as its third argument).
  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/dev-v0.1.3-dev.1567/saw-agent_dev-v0.1.3-dev.1567_darwin_arm64.tar.gz"
      sha256 "4a26bb78178aeec6f784c8d04e7f2eedbf66714458f5366f1283728212631d4b"
    else
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/dev-v0.1.3-dev.1567/saw-agent_dev-v0.1.3-dev.1567_darwin_amd64.tar.gz"
      sha256 "f48aad660042e0faca02e78e8964aa2b5a05cae10d05518f88c0aa55b0ba8a9c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/dev-v0.1.3-dev.1567/saw-agent_dev-v0.1.3-dev.1567_linux_arm64.tar.gz"
      sha256 "8144e44473f2dee19635788c36745d9fb65c202d28a64879d12702ca8d1fe15f"
    else
      url "https://github.com/LenderCom/saw-agent-releases/releases/download/dev-v0.1.3-dev.1567/saw-agent_dev-v0.1.3-dev.1567_linux_amd64.tar.gz"
      sha256 "5be3a15bd9e678d70554c1ec6a7ea13d26c812ee523d20aa1a8ca454bca656b9"
    end
  end

  # Named saw-agent-dev (not saw-agent) end to end — the shim on PATH, the keg, the class —
  # so it installs and links alongside the stable saw-agent formula without either
  # clobbering the other's /opt/homebrew/bin entry. One machine still runs one channel's
  # binary at a time in practice: whichever of the two you actually invoke is the one that
  # pairs, and its self-update writes the SAME ~/.saw/bin/saw-agent + ~/.saw/cloud/channel
  # the get.sawrun.com installer would (that installer has no dev/stable formula split —
  # it takes a --channel flag against one managed copy).
  def install
    libexec.install "saw-agent"
    (bin/"saw-agent-dev").write shim_script
    chmod 0755, bin/"saw-agent-dev"
  end

  def shim_script
    <<~SH
      #!/bin/bash
      # Generated by Formula/saw-agent-dev.rb — do not edit directly.
      managed="$HOME/.saw/bin/saw-agent"
      keg="#{opt_libexec}/saw-agent"

      # Same ENOEXEC footgun as the stable formula's shim (see Formula/saw-agent.rb) —
      # probe with a fast, side-effect-free flag before exec'ing the managed copy.
      if [ -x "$managed" ] && "$managed" -version >/dev/null 2>&1; then
        exec "$managed" "$@"
      fi

      exec "$keg" "$@"
    SH
  end

  def caveats
    <<~EOS
      DEV-CHANNEL build (#{version}), rebuilt several times a day — for use against a
      dev SAW workspace, not production.

      Set this machine up:

        saw-agent-dev setup

      It pairs, installs itself to start on boot, and walks you through the macOS
      permissions it needs — then asks two questions.

      Get the answers from your browser: open the dev SAW workspace, go to
      Settings -> Remote agents, and click "Add remote agent". The wizard shows the
      workspace id and a one-time pair code, in the order setup asks for them.

      The dev cloud origins are compiled in — nothing to export.

      Run `saw-agent-dev` (not `saw-agent`) — this installs alongside the stable
      formula under its own name.
    EOS
  end

  test do
    assert_match "saw-agent #{version}", shell_output("#{bin}/saw-agent-dev --version")
  end
end
